// 自分専用の頻出イディオム・定型表現データ。単語ランキングとは別の「イディオム」レベルで出題する。
const BUILTIN_IDIOMS = {
  en: [
    ["break the ice", "緊張をほぐす、打ち解ける", "I told a joke to break the ice."],
    ["hit the nail on the head", "核心を突く、図星を言う", "You hit the nail on the head."],
    ["piece of cake", "とても簡単なこと", "The test was a piece of cake."],
    ["once in a blue moon", "めったにない", "I eat out once in a blue moon."],
    ["under the weather", "体調がすぐれない", "I am feeling under the weather today."],
    ["cost an arm and a leg", "非常に高額である", "That car cost an arm and a leg."],
    ["let the cat out of the bag", "秘密を漏らす", "She let the cat out of the bag."],
    ["spill the beans", "秘密をばらす", "Who spilled the beans about the plan?"],
    ["beat around the bush", "遠回しに言う", "Stop beating around the bush and tell me."],
    ["call it a day", "今日はここまでにする", "Let us call it a day."],
    ["get the hang of", "コツをつかむ", "You will get the hang of it soon."],
    ["be on the same page", "認識を共有している", "Let us meet to make sure we are on the same page."],
    ["speak of the devil", "うわさをすれば現れる", "Speak of the devil, here he comes."],
    ["a blessing in disguise", "一見悪いが実は幸運なこと", "Losing that job was a blessing in disguise."],
    ["kill two birds with one stone", "一石二鳥を得る", "I killed two birds with one stone."],
    ["miss the boat", "好機を逃す", "We missed the boat on that deal."],
    ["pull someone's leg", "からかう、冗談を言う", "I am only pulling your leg."],
    ["go the extra mile", "期待以上に努力する", "She always goes the extra mile for clients."],
    ["hang in there", "あきらめずに頑張る", "Hang in there. You are almost done."],
    ["take it easy", "無理をしない、気楽にする", "Take it easy and get some rest."],
    ["make up one's mind", "決心する", "I cannot make up my mind."],
    ["run out of", "使い果たす、なくなる", "We ran out of coffee."],
    ["look forward to", "楽しみに待つ", "I look forward to hearing from you."],
    ["keep an eye on", "注意して見守る", "Please keep an eye on my bag."],
    ["in a nutshell", "簡単に言えば", "In a nutshell, we need more time."],
    ["at the end of the day", "結局のところ", "At the end of the day, quality matters."],
    ["so far, so good", "今のところ順調", "The new routine is working so far, so good."],
    ["give me a hand", "手を貸す", "Can you give me a hand with this box?"],
    ["take a break", "休憩する", "Let us take a break after this lesson."],
    ["figure out", "理解する、解決する", "I need time to figure it out."],
    ["add insult to injury", "踏んだり蹴ったりである", "To add insult to injury, the train was late."],
    ["actions speak louder than words", "行動は言葉より雄弁である", "Actions speak louder than words."],
    ["add fuel to the fire", "火に油を注ぐ", "His comment added fuel to the fire."],
    ["all ears", "熱心に聞く用意がある", "Tell me your idea. I am all ears."],
    ["back to square one", "振り出しに戻る", "The failed test sent us back to square one."],
    ["bark up the wrong tree", "見当違いをする", "If you blame me, you are barking up the wrong tree."],
    ["bite the bullet", "覚悟を決めて困難に立ち向かう", "I will bite the bullet and make the call."],
    ["break a leg", "幸運を祈る", "Break a leg in your performance tonight!"],
    ["call a spade a spade", "率直に言う", "She calls a spade a spade."],
    ["come rain or shine", "何があっても、必ず", "I will be there, come rain or shine."],
    ["cross that bridge when we come to it", "その時になってから考える", "We will cross that bridge when we come to it."],
    ["cry over spilled milk", "覆水盆に返らずと嘆く", "There is no use crying over spilled milk."],
    ["cut corners", "手を抜く、近道をする", "Do not cut corners on safety."],
    ["devil's advocate", "あえて反対意見を述べる人", "I will play devil's advocate for a moment."],
    ["easy does it", "ゆっくり慎重に", "Easy does it with that glass."],
    ["the elephant in the room", "誰も触れたがらない重大な問題", "We need to discuss the elephant in the room."],
    ["every cloud has a silver lining", "どんな悪いことにも良い面がある", "Every cloud has a silver lining."],
    ["get cold feet", "怖気づく", "He got cold feet before the interview."],
    ["get out of hand", "手に負えなくなる", "The party got out of hand."],
    ["give someone the benefit of the doubt", "人を信じて疑いを差し控える", "Let us give her the benefit of the doubt."],
    ["go with the flow", "流れに身を任せる", "I do not have a plan; I will go with the flow."],
    ["hang by a thread", "危うい状態である", "His job is hanging by a thread."],
    ["have bigger fish to fry", "もっと重要なことがある", "I have bigger fish to fry today."],
    ["hit the sack", "寝る", "I am tired, so I will hit the sack."],
    ["in hot water", "困った状況にある", "He is in hot water with his boss."],
    ["jump the gun", "早まった行動をする", "Do not jump the gun before we have the facts."],
    ["keep your chin up", "元気を出す", "Keep your chin up; things will improve."],
    ["the last straw", "我慢の限界", "That mistake was the last straw."],
    ["leave no stone unturned", "あらゆる手を尽くす", "We will leave no stone unturned."],
    ["let sleeping dogs lie", "寝た子を起こさない", "Let sleeping dogs lie and do not reopen the argument."],
    ["make ends meet", "収支を合わせて暮らす", "It is hard to make ends meet this month."],
    ["no pain, no gain", "努力なくして成果なし", "Training is difficult, but no pain, no gain."],
    ["off the hook", "責任や困難を免れて", "You are off the hook this time."],
    ["on the fence", "決めかねている", "I am still on the fence about moving."],
    ["once bitten, twice shy", "一度痛い目に遭うと用心深くなる", "Once bitten, twice shy, she checks every detail."],
    ["out of the blue", "突然に、思いがけず", "He called me out of the blue."],
    ["read between the lines", "行間を読む", "Read between the lines to understand her message."],
    ["a rule of thumb", "経験則、目安", "As a rule of thumb, save ten percent."],
    ["see eye to eye", "意見が一致する", "We do not always see eye to eye."],
    ["sit tight", "そのまま待つ", "Sit tight while I check the schedule."],
    ["speak your mind", "率直に意見を言う", "You can speak your mind here."],
    ["stand your ground", "自分の立場を守る", "She stood her ground during the negotiation."],
    ["take it with a grain of salt", "話を割り引いて聞く", "Take online rumors with a grain of salt."],
    ["the tip of the iceberg", "氷山の一角", "These costs are just the tip of the iceberg."],
    ["through thick and thin", "どんな時も、苦楽を共にして", "They stayed together through thick and thin."],
    ["throw in the towel", "諦める", "Do not throw in the towel yet."],
    ["under your nose", "すぐ目の前で", "The answer was right under your nose."],
    ["up in the air", "未定である", "Our travel plans are still up in the air."],
    ["when pigs fly", "絶対にありえない", "He will apologize when pigs fly."],
    ["you can say that again", "本当にその通り", "You can say that again; it was exhausting."],
    ["your guess is as good as mine", "私にもさっぱりわからない", "Your guess is as good as mine."],
    ["a dime a dozen", "ありふれたもの", "Cheap souvenirs are a dime a dozen."],
    ["at the drop of a hat", "すぐに、ためらわず", "She travels at the drop of a hat."],
    ["beat a dead horse", "無駄なことを蒸し返す", "There is no point beating a dead horse."],
    ["bend over backwards", "最大限努力する", "We bent over backwards to help them."],
    ["by the book", "規則どおりに", "Our auditor does everything by the book."],
    ["come in handy", "役に立つ", "This small tool will come in handy."],
    ["drop the ball", "失敗する、役割を怠る", "I dropped the ball on that deadline."],
    ["get a taste of your own medicine", "自分がしたことと同じ仕打ちを受ける", "He got a taste of his own medicine."],
    ["in the long run", "長い目で見れば", "This investment will help in the long run."],
    ["keep something under wraps", "秘密にしておく", "The company kept the launch under wraps."],
    ["know the ropes", "要領を知っている", "Ask Maya; she knows the ropes."],
    ["not my cup of tea", "私の好みではない", "Horror films are not my cup of tea."],
    ["on thin ice", "危うい立場で", "You are on thin ice after missing two meetings."],
    ["put all your eggs in one basket", "一つに全てを賭ける", "Do not put all your eggs in one basket."],
    ["rock the boat", "波風を立てる", "He did not want to rock the boat."],
    ["sleep on it", "一晩考える", "Do not decide now; sleep on it."],
    ["the whole nine yards", "ありったけ、全部", "They prepared the whole nine yards for the event."],
    ["wrap your head around", "理解する", "I am still wrapping my head around the news."],
    ["worth your while", "時間や労力をかける価値がある", "The course is worth your while."],
    ["zero in on", "焦点を絞る", "Let us zero in on the main issue."],
    ["a sight for sore eyes", "会えてうれしい人や光景", "You are a sight for sore eyes!"],
    ["all in a day's work", "いつもの仕事のうちである", "Fixing small problems is all in a day's work."],
    ["as luck would have it", "運よく、あいにく", "As luck would have it, we found a taxi."],
    ["at your fingertips", "すぐ利用できる状態で", "The information is at your fingertips."],
    ["the ball is in your court", "次はあなたの番である", "The ball is in your court now."],
    ["behind the scenes", "裏で、舞台裏で", "A lot happens behind the scenes."],
    ["blow off steam", "ストレスを発散する", "I go for a run to blow off steam."],
    ["break even", "収支がとんとんになる", "The shop broke even in its first year."],
    ["bring home the bacon", "生計を支える、成功する", "She works hard to bring home the bacon."],
    ["burn your bridges", "後戻りできないようにする", "Do not burn your bridges at work."],
    ["a change of heart", "気持ちの変化、翻意", "He had a change of heart and joined us."],
    ["come to terms with", "現実を受け入れる", "She is coming to terms with the news."],
    ["draw a blank", "何も思い出せない、空振りに終わる", "I drew a blank when asked his name."],
    ["face the music", "結果や批判を受け入れる", "It is time to face the music."],
    ["fall through", "計画などが失敗に終わる", "Our weekend plans fell through."],
    ["a far cry from", "〜とは大違いである", "This is a far cry from my old office."],
    ["find your feet", "新しい環境に慣れる", "It took me a month to find my feet."],
    ["fly off the handle", "かっとなる", "He flew off the handle over a small error."],
    ["from scratch", "ゼロから、最初から", "We built the website from scratch."],
    ["get the ball rolling", "事を始める", "Let us get the ball rolling."],
    ["get wind of", "〜をかぎつける、知る", "The press got wind of the plan."],
    ["give someone the cold shoulder", "人を冷たくあしらう", "She gave me the cold shoulder."],
    ["go bananas", "ひどく興奮する、取り乱す", "The fans went bananas after the win."],
    ["hold your horses", "ちょっと待つ", "Hold your horses; we are not ready."],
    ["in black and white", "明確に書面で", "Put the agreement in black and white."],
    ["in the same boat", "同じ困難な状況にいる", "We are all in the same boat."],
    ["keep something at bay", "〜を寄せつけない", "Exercise helps keep stress at bay."],
    ["last but not least", "最後になったが重要な", "Last but not least, thank you all."],
    ["lose touch", "連絡を絶つ、疎遠になる", "We lost touch after college."],
    ["make a long story short", "手短に言うと", "To make a long story short, we agreed."],
    ["off the record", "非公式に、内密に", "Off the record, the deal is nearly done."],
    ["on the same wavelength", "考え方が一致して", "We are finally on the same wavelength."],
    ["out of the question", "論外で、絶対に不可能で", "A delay is out of the question."],
    ["pull strings", "コネを使う", "He pulled strings to get an interview."],
    ["put your foot in your mouth", "失言する", "I really put my foot in my mouth."],
    ["raise the bar", "基準を引き上げる", "This design raises the bar."],
    ["run the show", "場を仕切る", "She runs the show around here."],
    ["save the day", "窮地を救う", "Your quick thinking saved the day."],
    ["shape things to come", "今後の成り行きを決める", "This decision will shape things to come."],
    ["sharp as a tack", "非常に頭が切れる", "My grandmother is sharp as a tack."],
    ["smooth sailing", "順調な進展", "After the update, it was smooth sailing."],
    ["in a split second", "一瞬で", "The decision was made in a split second."],
    ["steal someone's thunder", "人の手柄を横取りする", "I do not want to steal your thunder."],
    ["take the bull by the horns", "問題に果敢に立ち向かう", "She took the bull by the horns."],
    ["throw someone under the bus", "人に責任を押しつける", "He threw his teammate under the bus."],
    ["time flies", "時が経つのは早い", "Time flies when you are having fun."],
    ["turn a blind eye", "見て見ぬふりをする", "The manager turned a blind eye."],
    ["up to speed", "最新情報に通じて", "I will bring you up to speed."],
    ["water under the bridge", "過ぎたことで取り返せないこと", "It is water under the bridge now."]
  ],
  es: [
    ["estar en las nubes", "ぼんやりしている", "Hoy estás en las nubes."],
    ["costar un ojo de la cara", "非常に高い", "Ese teléfono cuesta un ojo de la cara."],
    ["meter la pata", "へまをする、失言する", "Creo que he metido la pata."],
    ["dar en el clavo", "核心を突く、図星を言う", "Has dado en el clavo."],
    ["ponerse las pilas", "気合を入れる、本気を出す", "Tengo que ponerme las pilas."],
    ["echar una mano", "手を貸す", "¿Puedes echarme una mano?"],
    ["ser pan comido", "朝飯前である", "El examen fue pan comido."],
    ["llover a cántaros", "土砂降りになる", "Está lloviendo a cántaros."],
    ["no tener pelos en la lengua", "歯に衣着せず言う", "Ella no tiene pelos en la lengua."],
    ["buscarle tres pies al gato", "余計に難しく考える", "No le busques tres pies al gato."],
    ["estar como una cabra", "風変わりである", "Mi vecino está como una cabra."],
    ["hacer la vista gorda", "見て見ぬふりをする", "El profesor hizo la vista gorda."],
    ["estar entre la espada y la pared", "板挟みになる", "Estoy entre la espada y la pared."],
    ["ponerse de acuerdo", "意見を合わせる、合意する", "Tenemos que ponernos de acuerdo."],
    ["matar dos pájaros de un tiro", "一石二鳥を得る", "Con este viaje matamos dos pájaros de un tiro."],
    ["llover sobre mojado", "悪いことが重なる", "La multa fue llover sobre mojado."],
    ["a lo hecho, pecho", "やったことは受け入れる", "A lo hecho, pecho y seguimos adelante."],
    ["irse por las ramas", "話を脱線させる", "No te vayas por las ramas."],
    ["quedarse de piedra", "非常に驚く", "Me quedé de piedra al oír la noticia."]
  ],
  fr: [
    ["avoir le cafard", "憂鬱な気分である", "J'ai le cafard aujourd'hui."],
    ["coûter les yeux de la tête", "非常に高い", "Cette voiture coûte les yeux de la tête."],
    ["poser un lapin", "約束をすっぽかす", "Il m'a posé un lapin."],
    ["donner un coup de main", "手を貸す", "Peux-tu me donner un coup de main ?"],
    ["tomber dans les pommes", "気絶する", "Elle est tombée dans les pommes."],
    ["mettre les pieds dans le plat", "失言する、気まずくする", "Il a mis les pieds dans le plat."],
    ["appeler un chat un chat", "率直に言う", "Il faut appeler un chat un chat."],
    ["être dans la lune", "ぼんやりしている", "Tu es dans la lune ce matin."],
    ["casser les pieds", "うんざりさせる", "Arrête de me casser les pieds."],
    ["chercher midi à quatorze heures", "余計に難しく考える", "Ne cherche pas midi à quatorze heures."],
    ["avoir un poil dans la main", "怠け者である", "Il a un poil dans la main."],
    ["ça marche", "うまくいく、了解", "D'accord, ça marche !"],
    ["mettre la main à la pâte", "自ら仕事を手伝う", "Tout le monde doit mettre la main à la pâte."],
    ["avoir la pêche", "元気いっぱいである", "Aujourd'hui, j'ai la pêche."],
    ["être dans le pétrin", "困った状況にある", "Nous sommes dans le pétrin."],
    ["raconter des salades", "でたらめを言う", "Il raconte encore des salades."],
    ["faire d'une pierre deux coups", "一石二鳥を得る", "Nous pouvons faire d'une pierre deux coups."],
    ["en avoir ras le bol", "うんざりする", "J'en ai ras le bol de cette situation."],
    ["faire la grasse matinée", "朝寝坊する", "Dimanche, je fais la grasse matinée."],
    ["avoir un coup de foudre", "一目ぼれする", "Elle a eu un coup de foudre."],
    ["prendre son temps", "時間をかけてゆっくりする", "Prends ton temps pour répondre."],
    ["tenir au courant", "知らせておく", "Tiens-moi au courant de la suite."],
    ["coûter un bras", "非常に高い", "Cette réparation va coûter un bras."],
    ["ne pas être dans son assiette", "体調や気分がすぐれない", "Je ne suis pas dans mon assiette aujourd'hui."],
    ["avoir le cœur sur la main", "気前がよく親切である", "Elle a le cœur sur la main."]
  ],
  de: [
    ["Tomaten auf den Augen haben", "大事なものを見落とす", "Du hast Tomaten auf den Augen."],
    ["die Daumen drücken", "幸運を祈る", "Ich drücke dir die Daumen."],
    ["ins Gras beißen", "死ぬ", "Der Held muss ins Gras beißen."],
    ["Schwein haben", "運がいい", "Du hast wirklich Schwein gehabt."],
    ["Bahnhof verstehen", "さっぱりわからない", "Ich verstehe nur Bahnhof."],
    ["die Nase voll haben", "うんざりしている", "Ich habe die Nase voll davon."],
    ["zwei Fliegen mit einer Klappe schlagen", "一石二鳥を得る", "Damit schlagen wir zwei Fliegen mit einer Klappe."],
    ["um den heißen Brei herumreden", "核心を避けて話す", "Rede nicht um den heißen Brei herum."],
    ["den Nagel auf den Kopf treffen", "核心を突く", "Du triffst den Nagel auf den Kopf."],
    ["die Katze aus dem Sack lassen", "秘密をばらす", "Jetzt lässt er die Katze aus dem Sack."],
    ["Da liegt der Hund begraben", "そこが問題の核心だ", "Da liegt der Hund begraben."],
    ["alles in Butter", "すべて順調である", "Keine Sorge, alles ist in Butter."],
    ["den Faden verlieren", "話の筋を見失う", "Entschuldigung, ich habe den Faden verloren."],
    ["aus allen Wolken fallen", "非常に驚く", "Sie fiel aus allen Wolken."],
    ["reinen Tisch machen", "洗いざらい話す", "Wir sollten reinen Tisch machen."],
    ["den Teufel an die Wand malen", "悪いことを想像して言う", "Mal nicht den Teufel an die Wand."],
    ["etwas auf die lange Bank schieben", "先延ばしにする", "Schieb die Entscheidung nicht auf die lange Bank."],
    ["Hals über Kopf", "大急ぎで、夢中になって", "Er verliebte sich Hals über Kopf."],
    ["das Handtuch werfen", "諦める", "Wir dürfen jetzt nicht das Handtuch werfen."],
    ["Nägel mit Köpfen machen", "本格的に実行する", "Jetzt machen wir Nägel mit Köpfen."],
    ["die Katze im Sack kaufen", "中身を確かめずに買う", "Kauf nicht die Katze im Sack."],
    ["kalte Füße bekommen", "怖気づく", "Vor der Prüfung bekam er kalte Füße."],
    ["auf der Leitung stehen", "理解が遅い、察しが悪い", "Ich stand wohl auf der Leitung."],
    ["unter vier Augen", "二人きりで", "Wir müssen unter vier Augen sprechen."]
  ],
  it: [
    ["in bocca al lupo", "幸運を祈る、頑張って", "In bocca al lupo per l'esame!"],
    ["costare un occhio della testa", "非常に高い", "Quella borsa costa un occhio della testa."],
    ["essere al settimo cielo", "大喜びしている", "Sono al settimo cielo."],
    ["avere le mani bucate", "浪費する", "Lui ha le mani bucate."],
    ["prendere due piccioni con una fava", "一石二鳥を得る", "Così prendiamo due piccioni con una fava."],
    ["piovere a catinelle", "土砂降りになる", "Piove a catinelle."],
    ["rompere il ghiaccio", "緊張をほぐす", "Una battuta può rompere il ghiaccio."],
    ["non vedere l'ora di", "心待ちにする", "Non vedo l'ora di partire."],
    ["avere la testa fra le nuvole", "ぼんやりしている", "Oggi hai la testa fra le nuvole."],
    ["fare orecchie da mercante", "聞こえないふりをする", "Fa orecchie da mercante."],
    ["in gamba", "有能な、しっかりした", "Sei proprio in gamba!"],
    ["essere in gamba", "有能である", "Lei è una persona in gamba."],
    ["non avere peli sulla lingua", "遠慮なく率直に言う", "Non ha peli sulla lingua."],
    ["in quattro e quattr'otto", "あっという間に", "Ha finito il lavoro in quattro e quattr'otto."],
    ["avere un diavolo per capello", "ひどく怒っている", "Oggi ha un diavolo per capello."],
    ["prendere lucciole per lanterne", "見当違いをする", "Hai preso lucciole per lanterne."],
    ["mettere il carro davanti ai buoi", "順序を逆にする", "Non mettere il carro davanti ai buoi."],
    ["acqua in bocca", "秘密を守る", "Acqua in bocca su questa notizia."],
    ["avere le mani in pasta", "深く関わっている", "Ha le mani in pasta nel progetto."],
    ["lasciare perdere", "あきらめる、放っておく", "Lasciamo perdere questa discussione."],
    ["dare una mano", "手を貸す", "Puoi darmi una mano?"],
    ["essere al verde", "お金がない", "Questo mese sono al verde."],
    ["vedere di buon occhio", "好意的に見る", "I miei genitori vedono di buon occhio la scelta."],
    ["rompere le uova nel paniere", "計画を台無しにする", "Non rompere le uova nel paniere."]
  ]
};
