// 自分専用の頻出イディオム・定型表現データ。単語ランキングとは別の「イディオム」レベルで出題する。
const BUILTIN_IDIOMS = {
  en: [
    ["break the ice", "緊張をほぐす、打ち解ける", "I told a joke to break the ice."],
    ["hit the nail on the head", "核心を突く、図星を言う", "You hit the nail on the head."],
    ["piece of cake", "とても簡単なこと", "The test was a piece of cake."],
    ["once in a blue moon", "めったにない", "I eat out once in a blue moon."],
    ["under the weather", "体調がすぐれない", "I am feeling under the weather today."],
    ["cost an arm and a leg", "非常に高額である", "That car cost an arm and a leg."],
    ["let the cat out of the bag", "秘密を漏らす", "She let the cat out of the bag."],
    ["spill the beans", "秘密をばらす", "Who spilled the beans about the plan?"],
    ["beat around the bush", "遠回しに言う", "Stop beating around the bush and tell me."],
    ["call it a day", "今日はここまでにする", "Let us call it a day."],
    ["get the hang of", "コツをつかむ", "You will get the hang of it soon."],
    ["be on the same page", "認識を共有している", "Let us meet to make sure we are on the same page."],
    ["speak of the devil", "うわさをすれば現れる", "Speak of the devil, here he comes."],
    ["a blessing in disguise", "一見悪いが実は幸運なこと", "Losing that job was a blessing in disguise."],
    ["kill two birds with one stone", "一石二鳥を得る", "I killed two birds with one stone."],
    ["miss the boat", "好機を逃す", "We missed the boat on that deal."],
    ["pull someone's leg", "からかう、冗談を言う", "I am only pulling your leg."],
    ["go the extra mile", "期待以上に努力する", "She always goes the extra mile for clients."],
    ["hang in there", "あきらめずに頑張る", "Hang in there. You are almost done."],
    ["take it easy", "無理をしない、気楽にする", "Take it easy and get some rest."],
    ["make up one's mind", "決心する", "I cannot make up my mind."],
    ["run out of", "使い果たす、なくなる", "We ran out of coffee."],
    ["look forward to", "楽しみに待つ", "I look forward to hearing from you."],
    ["keep an eye on", "注意して見守る", "Please keep an eye on my bag."],
    ["in a nutshell", "簡単に言えば", "In a nutshell, we need more time."],
    ["at the end of the day", "結局のところ", "At the end of the day, quality matters."],
    ["so far, so good", "今のところ順調", "The new routine is working so far, so good."],
    ["give me a hand", "手を貸す", "Can you give me a hand with this box?"],
    ["take a break", "休憩する", "Let us take a break after this lesson."],
    ["figure out", "理解する、解決する", "I need time to figure it out."],
    ["add insult to injury", "踏んだり蹴ったりである", "To add insult to injury, the train was late."],
    ["actions speak louder than words", "行動は言葉より雄弁である", "Actions speak louder than words."],
    ["add fuel to the fire", "火に油を注ぐ", "His comment added fuel to the fire."],
    ["all ears", "熱心に聞く用意がある", "Tell me your idea. I am all ears."],
    ["back to square one", "振り出しに戻る", "The failed test sent us back to square one."],
    ["bark up the wrong tree", "見当違いをする", "If you blame me, you are barking up the wrong tree."],
    ["bite the bullet", "覚悟を決めて困難に立ち向かう", "I will bite the bullet and make the call."],
    ["break a leg", "幸運を祈る", "Break a leg in your performance tonight!"],
    ["call a spade a spade", "率直に言う", "She calls a spade a spade."],
    ["come rain or shine", "何があっても、必ず", "I will be there, come rain or shine."],
    ["cross that bridge when we come to it", "その時になってから考える", "We will cross that bridge when we come to it."],
    ["cry over spilled milk", "覆水盆に返らずと嘆く", "There is no use crying over spilled milk."],
    ["cut corners", "手を抜く、近道をする", "Do not cut corners on safety."],
    ["devil's advocate", "あえて反対意見を述べる人", "I will play devil's advocate for a moment."],
    ["easy does it", "ゆっくり慎重に", "Easy does it with that glass."],
    ["the elephant in the room", "誰も触れたがらない重大な問題", "We need to discuss the elephant in the room."],
    ["every cloud has a silver lining", "どんな悪いことにも良い面がある", "Every cloud has a silver lining."],
    ["get cold feet", "怖気づく", "He got cold feet before the interview."],
    ["get out of hand", "手に負えなくなる", "The party got out of hand."],
    ["give someone the benefit of the doubt", "人を信じて疑いを差し控える", "Let us give her the benefit of the doubt."],
    ["go with the flow", "流れに身を任せる", "I do not have a plan; I will go with the flow."],
    ["hang by a thread", "危うい状態である", "His job is hanging by a thread."],
    ["have bigger fish to fry", "もっと重要なことがある", "I have bigger fish to fry today."],
    ["hit the sack", "寝る", "I am tired, so I will hit the sack."],
    ["in hot water", "困った状況にある", "He is in hot water with his boss."],
    ["jump the gun", "早まった行動をする", "Do not jump the gun before we have the facts."],
    ["keep your chin up", "元気を出す", "Keep your chin up; things will improve."],
    ["the last straw", "我慢の限界", "That mistake was the last straw."],
    ["leave no stone unturned", "あらゆる手を尽くす", "We will leave no stone unturned."],
    ["let sleeping dogs lie", "寝た子を起こさない", "Let sleeping dogs lie and do not reopen the argument."],
    ["make ends meet", "収支を合わせて暮らす", "It is hard to make ends meet this month."],
    ["no pain, no gain", "努力なくして成果なし", "Training is difficult, but no pain, no gain."],
    ["off the hook", "責任や困難を免れて", "You are off the hook this time."],
    ["on the fence", "決めかねている", "I am still on the fence about moving."],
    ["once bitten, twice shy", "一度痛い目に遭うと用心深くなる", "Once bitten, twice shy, she checks every detail."],
    ["out of the blue", "突然に、思いがけず", "He called me out of the blue."],
    ["read between the lines", "行間を読む", "Read between the lines to understand her message."],
    ["a rule of thumb", "経験則、目安", "As a rule of thumb, save ten percent."],
    ["see eye to eye", "意見が一致する", "We do not always see eye to eye."],
    ["sit tight", "そのまま待つ", "Sit tight while I check the schedule."],
    ["speak your mind", "率直に意見を言う", "You can speak your mind here."],
    ["stand your ground", "自分の立場を守る", "She stood her ground during the negotiation."],
    ["take it with a grain of salt", "話を割り引いて聞く", "Take online rumors with a grain of salt."],
    ["the tip of the iceberg", "氷山の一角", "These costs are just the tip of the iceberg."],
    ["through thick and thin", "どんな時も、苦楽を共にして", "They stayed together through thick and thin."],
    ["throw in the towel", "諦める", "Do not throw in the towel yet."],
    ["under your nose", "すぐ目の前で", "The answer was right under your nose."],
    ["up in the air", "未定である", "Our travel plans are still up in the air."],
    ["when pigs fly", "絶対にありえない", "He will apologize when pigs fly."],
    ["you can say that again", "本当にその通り", "You can say that again; it was exhausting."],
    ["your guess is as good as mine", "私にもさっぱりわからない", "Your guess is as good as mine."],
    ["a dime a dozen", "ありふれたもの", "Cheap souvenirs are a dime a dozen."],
    ["at the drop of a hat", "すぐに、ためらわず", "She travels at the drop of a hat."],
    ["beat a dead horse", "無駄なことを蒸し返す", "There is no point beating a dead horse."],
    ["bend over backwards", "最大限努力する", "We bent over backwards to help them."],
    ["by the book", "規則どおりに", "Our auditor does everything by the book."],
    ["come in handy", "役に立つ", "This small tool will come in handy."],
    ["drop the ball", "失敗する、役割を怠る", "I dropped the ball on that deadline."],
    ["get a taste of your own medicine", "自分がしたことと同じ仕打ちを受ける", "He got a taste of his own medicine."],
    ["in the long run", "長い目で見れば", "This investment will help in the long run."],
    ["keep something under wraps", "秘密にしておく", "The company kept the launch under wraps."],
    ["know the ropes", "要領を知っている", "Ask Maya; she knows the ropes."],
    ["not my cup of tea", "私の好みではない", "Horror films are not my cup of tea."],
    ["on thin ice", "危うい立場で", "You are on thin ice after missing two meetings."],
    ["put all your eggs in one basket", "一つに全てを賭ける", "Do not put all your eggs in one basket."],
    ["rock the boat", "波風を立てる", "He did not want to rock the boat."],
    ["sleep on it", "一晩考える", "Do not decide now; sleep on it."],
    ["the whole nine yards", "ありったけ、全部", "They prepared the whole nine yards for the event."],
    ["wrap your head around", "理解する", "I am still wrapping my head around the news."],
    ["worth your while", "時間や労力をかける価値がある", "The course is worth your while."],
    ["zero in on", "焦点を絞る", "Let us zero in on the main issue."],
    ["a sight for sore eyes", "会えてうれしい人や光景", "You are a sight for sore eyes!"],
    ["all in a day's work", "いつもの仕事のうちである", "Fixing small problems is all in a day's work."],
    ["as luck would have it", "運よく、あいにく", "As luck would have it, we found a taxi."],
    ["at your fingertips", "すぐ利用できる状態で", "The information is at your fingertips."],
    ["the ball is in your court", "次はあなたの番である", "The ball is in your court now."],
    ["behind the scenes", "裏で、舞台裏で", "A lot happens behind the scenes."],
    ["blow off steam", "ストレスを発散する", "I go for a run to blow off steam."],
    ["break even", "収支がとんとんになる", "The shop broke even in its first year."],
    ["bring home the bacon", "生計を支える、成功する", "She works hard to bring home the bacon."],
    ["burn your bridges", "後戻りできないようにする", "Do not burn your bridges at work."],
    ["a change of heart", "気持ちの変化、翻意", "He had a change of heart and joined us."],
    ["come to terms with", "現実を受け入れる", "She is coming to terms with the news."],
    ["draw a blank", "何も思い出せない、空振りに終わる", "I drew a blank when asked his name."],
    ["face the music", "結果や批判を受け入れる", "It is time to face the music."],
    ["fall through", "計画などが失敗に終わる", "Our weekend plans fell through."],
    ["a far cry from", "〜とは大違いである", "This is a far cry from my old office."],
    ["find your feet", "新しい環境に慣れる", "It took me a month to find my feet."],
    ["fly off the handle", "かっとなる", "He flew off the handle over a small error."],
    ["from scratch", "ゼロから、最初から", "We built the website from scratch."],
    ["get the ball rolling", "事を始める", "Let us get the ball rolling."],
    ["get wind of", "〜をかぎつける、知る", "The press got wind of the plan."],
    ["give someone the cold shoulder", "人を冷たくあしらう", "She gave me the cold shoulder."],
    ["go bananas", "ひどく興奮する、取り乱す", "The fans went bananas after the win."],
    ["hold your horses", "ちょっと待つ", "Hold your horses; we are not ready."],
    ["in black and white", "明確に書面で", "Put the agreement in black and white."],
    ["in the same boat", "同じ困難な状況にいる", "We are all in the same boat."],
    ["keep something at bay", "〜を寄せつけない", "Exercise helps keep stress at bay."],
    ["last but not least", "最後になったが重要な", "Last but not least, thank you all."],
    ["lose touch", "連絡を絶つ、疎遠になる", "We lost touch after college."],
    ["make a long story short", "手短に言うと", "To make a long story short, we agreed."],
    ["off the record", "非公式に、内密に", "Off the record, the deal is nearly done."],
    ["on the same wavelength", "考え方が一致して", "We are finally on the same wavelength."],
    ["out of the question", "論外で、絶対に不可能で", "A delay is out of the question."],
    ["pull strings", "コネを使う", "He pulled strings to get an interview."],
    ["put your foot in your mouth", "失言する", "I really put my foot in my mouth."],
    ["raise the bar", "基準を引き上げる", "This design raises the bar."],
    ["run the show", "場を仕切る", "She runs the show around here."],
    ["save the day", "窮地を救う", "Your quick thinking saved the day."],
    ["shape things to come", "今後の成り行きを決める", "This decision will shape things to come."],
    ["sharp as a tack", "非常に頭が切れる", "My grandmother is sharp as a tack."],
    ["smooth sailing", "順調な進展", "After the update, it was smooth sailing."],
    ["in a split second", "一瞬で", "The decision was made in a split second."],
    ["steal someone's thunder", "人の手柄を横取りする", "I do not want to steal your thunder."],
    ["take the bull by the horns", "問題に果敢に立ち向かう", "She took the bull by the horns."],
    ["throw someone under the bus", "人に責任を押しつける", "He threw his teammate under the bus."],
    ["time flies", "時が経つのは早い", "Time flies when you are having fun."],
    ["turn a blind eye", "見て見ぬふりをする", "The manager turned a blind eye."],
    ["up to speed", "最新情報に通じて", "I will bring you up to speed."],
    ["water under the bridge", "過ぎたことで取り返せないこと", "It is water under the bridge now."],
    ["a piece of the action", "活動や利益に参加すること", "Can I get a piece of the action?"],
    ["a slap on the wrist", "軽い罰、厳しくない処分", "He got a slap on the wrist for being late."],
    ["a tough nut to crack", "手ごわい問題や人", "This puzzle is a tough nut to crack."],
    ["alive and kicking", "元気で健在で", "The old tradition is still alive and kicking."],
    ["an armchair critic", "口だけの評論家", "It is easy to be an armchair critic."],
    ["the apple of someone's eye", "大切でかわいい人", "Her grandson is the apple of her eye."],
    ["as easy as pie", "とても簡単で", "The setup was as easy as pie."],
    ["as right as rain", "すっかり元気で", "After a good sleep, I felt as right as rain."],
    ["at odds", "意見が対立して", "The two teams are at odds over the plan."],
    ["back someone up", "人を支持する、助ける", "Thanks for backing me up in the meeting."],
    ["bad blood", "確執、わだかまり", "There is no bad blood between us."],
    ["be all set", "準備がすべて整っている", "We are all set for the trip."],
    ["be in charge", "責任者である", "Who is in charge of this project?"],
    ["be snowed under", "仕事に忙殺されている", "I am snowed under with emails."],
    ["be up to something", "何かたくらんでいる", "The children are up to something."],
    ["behind someone's back", "人のいないところで", "Do not talk about her behind her back."],
    ["better late than never", "遅くてもやらないよりまし", "You finally started—better late than never."],
    ["bite off more than you can chew", "自分の手に余ることを引き受ける", "I bit off more than I could chew."],
    ["break the news", "知らせを伝える", "Who will break the news to him?"],
    ["bring something up", "話題に持ち出す", "She brought up an important point."],
    ["brush up on", "〜を復習して磨きをかける", "I need to brush up on my French."],
    ["call the shots", "決定権を持つ", "She calls the shots here."],
    ["carry on", "続ける", "Please carry on with your work."],
    ["catch someone red-handed", "現行犯で捕まえる", "The guard caught him red-handed."],
    ["come across", "偶然見つける、出会う", "I came across an old photo."],
    ["come to mind", "思い浮かぶ", "A good example comes to mind."],
    ["count on", "頼りにする", "You can count on me."],
    ["crack down on", "厳しく取り締まる", "The city is cracking down on illegal parking."],
    ["cross your fingers", "幸運を祈る", "Cross your fingers for my interview."],
    ["cut to the chase", "本題に入る", "Let us cut to the chase."],
    ["do your best", "最善を尽くす", "Just do your best."],
    ["down to earth", "気取らない、現実的な", "She is friendly and down to earth."],
    ["draw the line", "一線を引く", "I draw the line at lying."],
    ["dress to kill", "とてもめかし込む", "She dressed to kill for the party."],
    ["drive someone crazy", "人をいらいらさせる", "That noise is driving me crazy."],
    ["face to face", "面と向かって", "We need to talk face to face."],
    ["fair and square", "公正に、正々堂々と", "They won fair and square."],
    ["few and far between", "非常に少ない、まれな", "Affordable homes are few and far between."],
    ["fit as a fiddle", "とても元気で健康な", "My grandfather is fit as a fiddle."],
    ["for good", "永久に、これを最後に", "She left the city for good."],
    ["from time to time", "時々", "We meet for coffee from time to time."],
    ["get carried away", "夢中になりすぎる", "I got carried away while shopping."],
    ["get over", "乗り越える、回復する", "It took time to get over the disappointment."],
    ["get rid of", "取り除く、処分する", "We need to get rid of old files."],
    ["get your act together", "気を引き締める", "You need to get your act together."],
    ["give it a shot", "試してみる", "I have never skied, but I will give it a shot."],
    ["give rise to", "〜を引き起こす", "The change gave rise to new problems."],
    ["go over", "詳しく検討する、復習する", "Let us go over the notes together."],
    ["go out of your way", "わざわざ努力する", "She went out of her way to help me."],
    ["go the distance", "最後までやり遂げる", "With practice, you can go the distance."],
    ["hang out", "ぶらぶら過ごす、遊ぶ", "Do you want to hang out after work?"],
    ["have a lot on your plate", "やることをたくさん抱えている", "I have a lot on my plate this week."],
    ["head over heels", "すっかり夢中になって", "He fell head over heels in love."],
    ["hit the road", "出発する", "We should hit the road early."],
    ["hold on", "待つ、つかまる", "Hold on a second, please."],
    ["in a pickle", "困った状況で", "I am in a pickle with this deadline."],
    ["in due course", "やがて、時が来れば", "You will hear the result in due course."],
    ["in no time", "すぐに、たちまち", "We will be there in no time."],
    ["in person", "本人が直接", "I would like to meet you in person."],
    ["in the nick of time", "ぎりぎり間に合って", "We arrived in the nick of time."],
    ["it goes without saying", "言うまでもない", "It goes without saying that safety comes first."],
    ["keep in mind", "心に留めておく", "Keep in mind that prices may change."],
    ["know by heart", "暗記している", "She knows the poem by heart."],
    ["lend a hand", "手を貸す", "Could you lend me a hand?"],
    ["the light at the end of the tunnel", "苦境の先の希望", "We can finally see the light at the end of the tunnel."],
    ["little by little", "少しずつ", "Little by little, my confidence grew."],
    ["look down on", "見下す", "Never look down on people."],
    ["make a difference", "違いを生む、役に立つ", "Small actions can make a difference."],
    ["make yourself at home", "くつろぐ", "Please make yourself at home."],
    ["meet halfway", "歩み寄る", "We should meet halfway on this issue."],
    ["miss the point", "要点を外す", "You are missing the point."],
    ["my hands are tied", "どうしようもない", "I would help, but my hands are tied."],
    ["no wonder", "道理で、〜も不思議ではない", "No wonder you are tired after that trip."],
    ["not rocket science", "難しいことではない", "The instructions are not rocket science."],
    ["now and then", "時々", "I still call him now and then."],
    ["odds are", "おそらく、可能性が高い", "Odds are, they will agree."],
    ["on purpose", "わざと", "I did not do it on purpose."],
    ["out of order", "故障中で、順序が乱れて", "The elevator is out of order."],
    ["over the moon", "大喜びして", "She was over the moon about the result."],
    ["pass the buck", "責任を押しつける", "Do not pass the buck to your team."],
    ["pay off", "報われる、完済する", "All your hard work will pay off."],
    ["pick up", "身につける、拾う", "I picked up some useful phrases."],
    ["play it by ear", "成り行きに任せる", "We have no fixed plan; we will play it by ear."],
    ["point out", "指摘する", "She pointed out a small error."],
    ["pull yourself together", "気を取り直す", "Pull yourself together and try again."],
    ["put off", "延期する、先延ばしにする", "Do not put off the decision."],
    ["rain cats and dogs", "土砂降りになる", "It is raining cats and dogs."],
    ["ring a bell", "聞き覚えがある", "That name rings a bell."],
    ["run out of steam", "気力が尽きる", "I ran out of steam near the end."],
    ["safe and sound", "無事に", "They arrived safe and sound."],
    ["see the light", "理解する、希望を見いだす", "He finally saw the light."],
    ["set in stone", "変更できない、確定した", "The schedule is not set in stone."],
    ["show up", "現れる、姿を見せる", "He did not show up for the meeting."],
    ["sooner or later", "遅かれ早かれ", "Sooner or later, you will understand."],
    ["stand out", "目立つ、際立つ", "Her application stood out."],
    ["stick to your guns", "自分の主張を貫く", "Stick to your guns if you believe you are right."],
    ["take advantage of", "利用する、活用する", "Take advantage of this opportunity."],
    ["take for granted", "当然と思う、ありがたみを忘れる", "Do not take clean water for granted."],
    ["take place", "起こる、開催される", "The event will take place on Friday."],
    ["take responsibility", "責任を取る", "He took responsibility for the mistake."],
    ["talk shop", "仕事の話をする", "We promised not to talk shop tonight."],
    ["the bottom line", "結論、最重要点", "The bottom line is that we need more time."],
    ["think outside the box", "型にはまらず考える", "We need to think outside the box."],
    ["throw in", "おまけで加える", "They threw in free delivery."],
    ["tighten your belt", "節約する", "We need to tighten our belts this month."],
    ["touch base", "連絡を取る", "I will touch base with you tomorrow."],
    ["turn down", "断る、音量を下げる", "She turned down the offer."],
    ["turn out", "結果的に〜となる", "The plan turned out well."],
    ["up to you", "あなた次第で", "The choice is up to you."],
    ["wear out", "使い古す、疲れ果てさせる", "These shoes are worn out."],
    ["word of mouth", "口コミ", "The café grew through word of mouth."]
  ],
  es: [
    ["estar en las nubes", "ぼんやりしている", "Hoy estás en las nubes."],
    ["costar un ojo de la cara", "非常に高い", "Ese teléfono cuesta un ojo de la cara."],
    ["meter la pata", "へまをする、失言する", "Creo que he metido la pata."],
    ["dar en el clavo", "核心を突く、図星を言う", "Has dado en el clavo."],
    ["ponerse las pilas", "気合を入れる、本気を出す", "Tengo que ponerme las pilas."],
    ["echar una mano", "手を貸す", "¿Puedes echarme una mano?"],
    ["ser pan comido", "朝飯前である", "El examen fue pan comido."],
    ["llover a cántaros", "土砂降りになる", "Está lloviendo a cántaros."],
    ["no tener pelos en la lengua", "歯に衣着せず言う", "Ella no tiene pelos en la lengua."],
    ["buscarle tres pies al gato", "余計に難しく考える", "No le busques tres pies al gato."],
    ["estar como una cabra", "風変わりである", "Mi vecino está como una cabra."],
    ["hacer la vista gorda", "見て見ぬふりをする", "El profesor hizo la vista gorda."],
    ["estar entre la espada y la pared", "板挟みになる", "Estoy entre la espada y la pared."],
    ["ponerse de acuerdo", "意見を合わせる、合意する", "Tenemos que ponernos de acuerdo."],
    ["matar dos pájaros de un tiro", "一石二鳥を得る", "Con este viaje matamos dos pájaros de un tiro."],
    ["llover sobre mojado", "悪いことが重なる", "La multa fue llover sobre mojado."],
    ["a lo hecho, pecho", "やったことは受け入れる", "A lo hecho, pecho y seguimos adelante."],
    ["irse por las ramas", "話を脱線させる", "No te vayas por las ramas."],
    ["quedarse de piedra", "非常に驚く", "Me quedé de piedra al oír la noticia."],
    ["estar de acuerdo", "賛成する、意見が一致する", "Estoy de acuerdo contigo."],
    ["tener razón", "正しい、道理がある", "Creo que tienes razón."],
    ["tener ganas de", "〜したい気がする", "Tengo ganas de viajar."],
    ["dar igual", "どちらでもよい、構わない", "Me da igual dónde cenemos."],
    ["hacer falta", "必要である", "Hace falta más tiempo."],
    ["darse cuenta de", "気づく", "Me di cuenta del error."],
    ["llevarse bien", "仲良くする", "Nos llevamos muy bien."],
    ["caer bien", "感じがよい、気に入る", "Tu hermana me cae muy bien."],
    ["echar de menos", "恋しく思う", "Echo de menos mi ciudad."],
    ["tener en cuenta", "考慮に入れる", "Ten en cuenta este consejo."],
    ["por si acaso", "念のため", "Lleva un paraguas por si acaso."],
    ["de vez en cuando", "時々", "Salimos a cenar de vez en cuando."],
    ["en seguida", "すぐに", "Voy en seguida."],
    ["a fin de cuentas", "結局のところ", "A fin de cuentas, fue una buena decisión."],
    ["sin pelos en la lengua", "遠慮なく率直に", "Habla sin pelos en la lengua."],
    ["estar hecho polvo", "へとへとである", "Después del viaje estoy hecho polvo."],
    ["no dar pie con bola", "何をしてもうまくいかない", "Hoy no doy pie con bola."],
    ["poner toda la carne en el asador", "全力を尽くす", "Pondremos toda la carne en el asador."],
    ["salir a pedir de boca", "思い通りにうまくいく", "La reunión salió a pedir de boca."],
    ["tener la sartén por el mango", "主導権を握る", "Ahora ella tiene la sartén por el mango."],
    ["estar de bote en bote", "満員である", "El tren estaba de bote en bote."],
    ["no pegar ojo", "一睡もできない", "Anoche no pegué ojo."],
    ["dar en el blanco", "的を射る", "Tu comentario dio en el blanco."],
    ["poner los puntos sobre las íes", "要点をはっきりさせる", "Hay que poner los puntos sobre las íes."],
    ["estar al tanto", "事情を把握している", "Mantente al tanto de las novedades."],
    ["por lo visto", "どうやら、見るところでは", "Por lo visto, ya se fueron."],
    ["de repente", "突然に", "De repente empezó a llover."],
    ["al pie de la letra", "文字どおりに、厳密に", "Sigue las instrucciones al pie de la letra."],
    ["a largo plazo", "長期的に", "Es una inversión a largo plazo."],
    ["en un abrir y cerrar de ojos", "あっという間に", "Todo cambió en un abrir y cerrar de ojos."],
    ["estar como pez en el agua", "水を得た魚のように慣れている", "En este trabajo está como pez en el agua."],
    ["no hay mal que por bien no venga", "悪いことにも良い面がある", "No hay mal que por bien no venga."],
    ["más vale tarde que nunca", "遅くてもやらないよりまし", "Más vale tarde que nunca."]
  ],
  fr: [
    ["avoir le cafard", "憂鬱な気分である", "J'ai le cafard aujourd'hui."],
    ["coûter les yeux de la tête", "非常に高い", "Cette voiture coûte les yeux de la tête."],
    ["poser un lapin", "約束をすっぽかす", "Il m'a posé un lapin."],
    ["donner un coup de main", "手を貸す", "Peux-tu me donner un coup de main ?"],
    ["tomber dans les pommes", "気絶する", "Elle est tombée dans les pommes."],
    ["mettre les pieds dans le plat", "失言する、気まずくする", "Il a mis les pieds dans le plat."],
    ["appeler un chat un chat", "率直に言う", "Il faut appeler un chat un chat."],
    ["être dans la lune", "ぼんやりしている", "Tu es dans la lune ce matin."],
    ["casser les pieds", "うんざりさせる", "Arrête de me casser les pieds."],
    ["chercher midi à quatorze heures", "余計に難しく考える", "Ne cherche pas midi à quatorze heures."],
    ["avoir un poil dans la main", "怠け者である", "Il a un poil dans la main."],
    ["ça marche", "うまくいく、了解", "D'accord, ça marche !"],
    ["mettre la main à la pâte", "自ら仕事を手伝う", "Tout le monde doit mettre la main à la pâte."],
    ["avoir la pêche", "元気いっぱいである", "Aujourd'hui, j'ai la pêche."],
    ["être dans le pétrin", "困った状況にある", "Nous sommes dans le pétrin."],
    ["raconter des salades", "でたらめを言う", "Il raconte encore des salades."],
    ["faire d'une pierre deux coups", "一石二鳥を得る", "Nous pouvons faire d'une pierre deux coups."],
    ["en avoir ras le bol", "うんざりする", "J'en ai ras le bol de cette situation."],
    ["faire la grasse matinée", "朝寝坊する", "Dimanche, je fais la grasse matinée."],
    ["avoir un coup de foudre", "一目ぼれする", "Elle a eu un coup de foudre."],
    ["prendre son temps", "時間をかけてゆっくりする", "Prends ton temps pour répondre."],
    ["tenir au courant", "知らせておく", "Tiens-moi au courant de la suite."],
    ["coûter un bras", "非常に高い", "Cette réparation va coûter un bras."],
    ["ne pas être dans son assiette", "体調や気分がすぐれない", "Je ne suis pas dans mon assiette aujourd'hui."],
    ["avoir le cœur sur la main", "気前がよく親切である", "Elle a le cœur sur la main."],
    ["être d'accord", "賛成する、意見が一致する", "Je suis d'accord avec toi."],
    ["avoir envie de", "〜したい気がする", "J'ai envie de voyager."],
    ["avoir besoin de", "〜を必要とする", "J'ai besoin de ton aide."],
    ["se rendre compte de", "気づく", "Je me suis rendu compte de mon erreur."],
    ["s'entendre bien", "仲がよい", "Nous nous entendons bien."],
    ["manquer à quelqu'un", "人を恋しく思わせる", "Tu me manques beaucoup."],
    ["tenir compte de", "考慮に入れる", "Il faut tenir compte des coûts."],
    ["au cas où", "万一に備えて", "Prends un manteau au cas où."],
    ["de temps en temps", "時々", "Je lis ce journal de temps en temps."],
    ["tout à coup", "突然に", "Tout à coup, il a disparu."],
    ["à long terme", "長期的に", "C'est utile à long terme."],
    ["à court terme", "短期的に", "Nous cherchons une solution à court terme."],
    ["à la lettre", "文字どおりに、厳密に", "Il a suivi la consigne à la lettre."],
    ["en un clin d'œil", "あっという間に", "Le travail était terminé en un clin d'œil."],
    ["être comme un poisson dans l'eau", "非常に慣れている", "Elle est comme un poisson dans l'eau ici."],
    ["mieux vaut tard que jamais", "遅くてもやらないよりまし", "Mieux vaut tard que jamais."],
    ["après la pluie, le beau temps", "苦の後には楽が来る", "Après la pluie, le beau temps."],
    ["prendre la mouche", "腹を立てる", "Ne prends pas la mouche pour si peu."],
    ["avoir un chat dans la gorge", "声がかすれる", "J'ai un chat dans la gorge ce matin."],
    ["couper la poire en deux", "折半する、歩み寄る", "Nous pouvons couper la poire en deux."],
    ["faire la sourde oreille", "聞こえないふりをする", "Il fait la sourde oreille à nos demandes."],
    ["jeter l'éponge", "諦める", "Ne jette pas l'éponge maintenant."],
    ["mettre de l'eau dans son vin", "態度を和らげる", "Il doit mettre de l'eau dans son vin."],
    ["ne pas mâcher ses mots", "遠慮なく率直に言う", "Elle ne mâche pas ses mots."],
    ["voir rouge", "激怒する", "Il voit rouge quand on le critique."],
    ["avoir la tête sur les épaules", "しっかりして現実的である", "Elle a la tête sur les épaules."],
    ["prendre son mal en patience", "辛抱強く耐える", "Il faut prendre son mal en patience."],
    ["mettre les bouchées doubles", "ペースを上げて努力する", "Nous devons mettre les bouchées doubles."],
    ["être au bout du rouleau", "疲れ果てている", "Je suis au bout du rouleau."],
    ["donner sa langue au chat", "さじを投げて答えを求める", "Je donne ma langue au chat."],
    ["faire mouche", "的を射る、成功する", "Sa remarque a fait mouche."],
    ["tenir la route", "しっかり通用する", "Son idée tient la route."]
  ],
  de: [
    ["Tomaten auf den Augen haben", "大事なものを見落とす", "Du hast Tomaten auf den Augen."],
    ["die Daumen drücken", "幸運を祈る", "Ich drücke dir die Daumen."],
    ["ins Gras beißen", "死ぬ", "Der Held muss ins Gras beißen."],
    ["Schwein haben", "運がいい", "Du hast wirklich Schwein gehabt."],
    ["Bahnhof verstehen", "さっぱりわからない", "Ich verstehe nur Bahnhof."],
    ["zwei Fliegen mit einer Klappe schlagen", "一石二鳥を得る", "Damit schlagen wir zwei Fliegen mit einer Klappe."],
    ["um den heißen Brei herumreden", "核心を避けて話す", "Rede nicht um den heißen Brei herum."],
    ["den Nagel auf den Kopf treffen", "核心を突く", "Du triffst den Nagel auf den Kopf."],
    ["die Katze aus dem Sack lassen", "秘密をばらす", "Jetzt lässt er die Katze aus dem Sack."],
    ["Da liegt der Hund begraben", "そこが問題の核心だ", "Da liegt der Hund begraben."],
    ["alles in Butter", "すべて順調である", "Keine Sorge, alles ist in Butter."],
    ["den Faden verlieren", "話の筋を見失う", "Entschuldigung, ich habe den Faden verloren."],
    ["aus allen Wolken fallen", "非常に驚く", "Sie fiel aus allen Wolken."],
    ["reinen Tisch machen", "洗いざらい話す", "Wir sollten reinen Tisch machen."],
    ["den Teufel an die Wand malen", "悪いことを想像して言う", "Mal nicht den Teufel an die Wand."],
    ["etwas auf die lange Bank schieben", "先延ばしにする", "Schieb die Entscheidung nicht auf die lange Bank."],
    ["Hals über Kopf", "大急ぎで、夢中になって", "Er verliebte sich Hals über Kopf."],
    ["das Handtuch werfen", "諦める", "Wir dürfen jetzt nicht das Handtuch werfen."],
    ["Nägel mit Köpfen machen", "本格的に実行する", "Jetzt machen wir Nägel mit Köpfen."],
    ["die Katze im Sack kaufen", "中身を確かめずに買う", "Kauf nicht die Katze im Sack."],
    ["kalte Füße bekommen", "怖気づく", "Vor der Prüfung bekam er kalte Füße."],
    ["auf der Leitung stehen", "理解が遅い、察しが悪い", "Ich stand wohl auf der Leitung."],
    ["unter vier Augen", "二人きりで", "Wir müssen unter vier Augen sprechen."],
    ["sich einig sein", "意見が一致する", "Wir sind uns in diesem Punkt einig."],
    ["Lust haben auf", "〜したい気がする", "Ich habe Lust auf einen Spaziergang."],
    ["Bescheid wissen", "事情をよく知っている", "Sie weiß über alles Bescheid."],
    ["sich etwas merken", "覚えておく", "Merk dir bitte diese Nummer."],
    ["sich gut verstehen", "仲がよい", "Wir verstehen uns sehr gut."],
    ["sich um etwas kümmern", "〜の面倒を見る、取り組む", "Ich kümmere mich darum."],
    ["in Betracht ziehen", "考慮に入れる", "Wir ziehen alle Optionen in Betracht."],
    ["im Voraus", "前もって", "Vielen Dank im Voraus."],
    ["ab und zu", "時々", "Ich gehe ab und zu ins Kino."],
    ["auf jeden Fall", "必ず、とにかく", "Ich komme auf jeden Fall."],
    ["auf keinen Fall", "絶対に〜ない", "Das mache ich auf keinen Fall."],
    ["im Handumdrehen", "あっという間に", "Er erledigt das im Handumdrehen."],
    ["auf lange Sicht", "長期的には", "Auf lange Sicht lohnt es sich."],
    ["Schritt für Schritt", "一歩ずつ", "Wir lernen Schritt für Schritt."],
    ["besser spät als nie", "遅くてもやらないよりまし", "Besser spät als nie."],
    ["Übung macht den Meister", "習うより慣れよ", "Übung macht den Meister."],
    ["Ende gut, alles gut", "終わりよければすべてよし", "Ende gut, alles gut."],
    ["die Kirche im Dorf lassen", "大げさにしない", "Lass die Kirche im Dorf."],
    ["jemandem die Daumen drücken", "人の幸運を祈る", "Ich drücke dir die Daumen."],
    ["sich etwas zu Herzen nehmen", "〜を深刻に受け止める", "Nimm dir die Kritik nicht zu Herzen."],
    ["den Kopf verlieren", "冷静さを失う", "Verlier jetzt nicht den Kopf."],
    ["den Kürzeren ziehen", "割を食う、負ける", "Am Ende zog er den Kürzeren."],
    ["die Kurve kratzen", "急いで立ち去る", "Wir müssen jetzt die Kurve kratzen."],
    ["aus dem Stegreif", "即興で、準備なしに", "Sie hielt die Rede aus dem Stegreif."],
    ["keine Ahnung haben", "さっぱりわからない", "Ich habe keine Ahnung."],
    ["auf dem Holzweg sein", "見当違いをする", "Du bist auf dem Holzweg."],
    ["jemandem auf der Tasche liegen", "人に金銭的に頼る", "Er liegt seinen Eltern auf der Tasche."],
    ["sich aus dem Staub machen", "逃げる、立ち去る", "Er machte sich aus dem Staub."],
    ["die Flinte ins Korn werfen", "諦める", "Wir werfen die Flinte nicht ins Korn."],
    ["reinen Wein einschenken", "本当のことを話す", "Schenk mir reinen Wein ein."],
    ["ins Fettnäpfchen treten", "失言する、へまをする", "Er trat ins Fettnäpfchen."],
    ["sich den Kopf zerbrechen", "頭を悩ませる", "Ich zerbreche mir den Kopf darüber."],
    ["die Nase voll haben", "うんざりしている", "Ich habe die Nase voll davon."],
    ["etwas auf die Reihe kriegen", "物事をうまく処理する", "Wir kriegen das schon auf die Reihe."]
  ],
  it: [
    ["in bocca al lupo", "幸運を祈る、頑張って", "In bocca al lupo per l'esame!"],
    ["costare un occhio della testa", "非常に高い", "Quella borsa costa un occhio della testa."],
    ["essere al settimo cielo", "大喜びしている", "Sono al settimo cielo."],
    ["avere le mani bucate", "浪費する", "Lui ha le mani bucate."],
    ["prendere due piccioni con una fava", "一石二鳥を得る", "Così prendiamo due piccioni con una fava."],
    ["piovere a catinelle", "土砂降りになる", "Piove a catinelle."],
    ["rompere il ghiaccio", "緊張をほぐす", "Una battuta può rompere il ghiaccio."],
    ["non vedere l'ora di", "心待ちにする", "Non vedo l'ora di partire."],
    ["avere la testa fra le nuvole", "ぼんやりしている", "Oggi hai la testa fra le nuvole."],
    ["fare orecchie da mercante", "聞こえないふりをする", "Fa orecchie da mercante."],
    ["in gamba", "有能な、しっかりした", "Sei proprio in gamba!"],
    ["essere in gamba", "有能である", "Lei è una persona in gamba."],
    ["non avere peli sulla lingua", "遠慮なく率直に言う", "Non ha peli sulla lingua."],
    ["in quattro e quattr'otto", "あっという間に", "Ha finito il lavoro in quattro e quattr'otto."],
    ["avere un diavolo per capello", "ひどく怒っている", "Oggi ha un diavolo per capello."],
    ["prendere lucciole per lanterne", "見当違いをする", "Hai preso lucciole per lanterne."],
    ["mettere il carro davanti ai buoi", "順序を逆にする", "Non mettere il carro davanti ai buoi."],
    ["acqua in bocca", "秘密を守る", "Acqua in bocca su questa notizia."],
    ["avere le mani in pasta", "深く関わっている", "Ha le mani in pasta nel progetto."],
    ["lasciare perdere", "あきらめる、放っておく", "Lasciamo perdere questa discussione."],
    ["dare una mano", "手を貸す", "Puoi darmi una mano?"],
    ["essere al verde", "お金がない", "Questo mese sono al verde."],
    ["vedere di buon occhio", "好意的に見る", "I miei genitori vedono di buon occhio la scelta."],
    ["rompere le uova nel paniere", "計画を台無しにする", "Non rompere le uova nel paniere."],
    ["essere d'accordo", "賛成する、意見が一致する", "Sono d'accordo con te."],
    ["avere voglia di", "〜したい気がする", "Ho voglia di viaggiare."],
    ["avere bisogno di", "〜を必要とする", "Ho bisogno del tuo aiuto."],
    ["rendersi conto di", "気づく", "Mi sono reso conto dell'errore."],
    ["andare d'accordo", "仲がよい、うまくいく", "Andiamo d'accordo da anni."],
    ["sentire la mancanza di", "〜を恋しく思う", "Sento la mancanza della mia famiglia."],
    ["tenere conto di", "考慮に入れる", "Dobbiamo tenere conto dei costi."],
    ["per sicurezza", "念のため", "Porta una giacca per sicurezza."],
    ["ogni tanto", "時々", "Ci vediamo ogni tanto."],
    ["all'improvviso", "突然に", "All'improvviso ha iniziato a piovere."],
    ["a lungo termine", "長期的に", "È una scelta utile a lungo termine."],
    ["in un batter d'occhio", "あっという間に", "Ha finito tutto in un batter d'occhio."],
    ["essere come un pesce nell'acqua", "非常に慣れている", "Qui è come un pesce nell'acqua."],
    ["meglio tardi che mai", "遅くてもやらないよりまし", "Meglio tardi che mai."],
    ["dopo la pioggia viene il sereno", "苦の後には楽が来る", "Dopo la pioggia viene il sereno."],
    ["prendere un granchio", "勘違いする、間違える", "Ho preso un granchio."],
    ["tagliare la corda", "逃げる、立ち去る", "È meglio tagliare la corda."],
    ["vuotare il sacco", "洗いざらい話す", "Adesso vuota il sacco."],
    ["avere la testa sulle spalle", "しっかりして現実的である", "Lei ha la testa sulle spalle."],
    ["non vedere l'ora", "待ちきれない", "Non vedo l'ora di partire."],
    ["fare finta di niente", "何もなかったふりをする", "Fa finta di niente."],
    ["mettere il dito nella piaga", "痛いところを突く", "Hai messo il dito nella piaga."],
    ["avere un asso nella manica", "秘策を持っている", "Ho ancora un asso nella manica."],
    ["menare il can per l'aia", "遠回しに話す", "Smettila di menare il can per l'aia."],
    ["cascare dalle nuvole", "非常に驚く", "Sono cascato dalle nuvole."],
    ["fare il passo più lungo della gamba", "身の丈以上のことをする", "Non fare il passo più lungo della gamba."],
    ["lasciare il tempo che trova", "あまり意味や効果がない", "Questa scusa lascia il tempo che trova."],
    ["essere con l'acqua alla gola", "非常に困っている", "Sono con l'acqua alla gola."]
  ]
};
