// 自分専用の頻出イディオム・定型表現データ。単語ランキングとは別の「イディオム」レベルで出題する。
const BUILTIN_IDIOMS = {
  en: [
    ["break the ice", "緊張をほぐす、打ち解ける", "I told a joke to break the ice."],
    ["hit the nail on the head", "核心を突く、図星を言う", "You hit the nail on the head."],
    ["piece of cake", "とても簡単なこと", "The test was a piece of cake."],
    ["once in a blue moon", "めったにない", "I eat out once in a blue moon."],
    ["under the weather", "体調がすぐれない", "I am feeling under the weather today."],
    ["cost an arm and a leg", "非常に高額である", "That car cost an arm and a leg."],
    ["let the cat out of the bag", "秘密を漏らす", "She let the cat out of the bag."],
    ["spill the beans", "秘密をばらす", "Who spilled the beans about the plan?"],
    ["beat around the bush", "遠回しに言う", "Stop beating around the bush and tell me."],
    ["call it a day", "今日はここまでにする", "Let us call it a day."],
    ["get the hang of", "コツをつかむ", "You will get the hang of it soon."],
    ["be on the same page", "認識を共有している", "Let us meet to make sure we are on the same page."],
    ["speak of the devil", "うわさをすれば現れる", "Speak of the devil, here he comes."],
    ["a blessing in disguise", "一見悪いが実は幸運なこと", "Losing that job was a blessing in disguise."],
    ["kill two birds with one stone", "一石二鳥を得る", "I killed two birds with one stone."],
    ["miss the boat", "好機を逃す", "We missed the boat on that deal."],
    ["pull someone's leg", "からかう、冗談を言う", "I am only pulling your leg."],
    ["go the extra mile", "期待以上に努力する", "She always goes the extra mile for clients."],
    ["hang in there", "あきらめずに頑張る", "Hang in there. You are almost done."],
    ["take it easy", "無理をしない、気楽にする", "Take it easy and get some rest."],
    ["make up one's mind", "決心する", "I cannot make up my mind."],
    ["run out of", "使い果たす、なくなる", "We ran out of coffee."],
    ["look forward to", "楽しみに待つ", "I look forward to hearing from you."],
    ["keep an eye on", "注意して見守る", "Please keep an eye on my bag."],
    ["in a nutshell", "簡単に言えば", "In a nutshell, we need more time."],
    ["at the end of the day", "結局のところ", "At the end of the day, quality matters."],
    ["so far, so good", "今のところ順調", "The new routine is working so far, so good."],
    ["give me a hand", "手を貸す", "Can you give me a hand with this box?"],
    ["take a break", "休憩する", "Let us take a break after this lesson."],
    ["figure out", "理解する、解決する", "I need time to figure it out."]
  ],
  es: [
    ["estar en las nubes", "ぼんやりしている", "Hoy estás en las nubes."],
    ["costar un ojo de la cara", "非常に高い", "Ese teléfono cuesta un ojo de la cara."],
    ["meter la pata", "へまをする、失言する", "Creo que he metido la pata."],
    ["dar en el clavo", "核心を突く、図星を言う", "Has dado en el clavo."],
    ["ponerse las pilas", "気合を入れる、本気を出す", "Tengo que ponerme las pilas."],
    ["echar una mano", "手を貸す", "¿Puedes echarme una mano?"],
    ["ser pan comido", "朝飯前である", "El examen fue pan comido."],
    ["llover a cántaros", "土砂降りになる", "Está lloviendo a cántaros."],
    ["no tener pelos en la lengua", "歯に衣着せず言う", "Ella no tiene pelos en la lengua."],
    ["buscarle tres pies al gato", "余計に難しく考える", "No le busques tres pies al gato."],
    ["estar como una cabra", "風変わりである", "Mi vecino está como una cabra."],
    ["hacer la vista gorda", "見て見ぬふりをする", "El profesor hizo la vista gorda."]
  ],
  fr: [
    ["avoir le cafard", "憂鬱な気分である", "J'ai le cafard aujourd'hui."],
    ["coûter les yeux de la tête", "非常に高い", "Cette voiture coûte les yeux de la tête."],
    ["poser un lapin", "約束をすっぽかす", "Il m'a posé un lapin."],
    ["donner un coup de main", "手を貸す", "Peux-tu me donner un coup de main ?"],
    ["tomber dans les pommes", "気絶する", "Elle est tombée dans les pommes."],
    ["mettre les pieds dans le plat", "失言する、気まずくする", "Il a mis les pieds dans le plat."],
    ["appeler un chat un chat", "率直に言う", "Il faut appeler un chat un chat."],
    ["être dans la lune", "ぼんやりしている", "Tu es dans la lune ce matin."],
    ["casser les pieds", "うんざりさせる", "Arrête de me casser les pieds."],
    ["chercher midi à quatorze heures", "余計に難しく考える", "Ne cherche pas midi à quatorze heures."],
    ["avoir un poil dans la main", "怠け者である", "Il a un poil dans la main."],
    ["ça marche", "うまくいく、了解", "D'accord, ça marche !"]
  ],
  de: [
    ["Tomaten auf den Augen haben", "大事なものを見落とす", "Du hast Tomaten auf den Augen."],
    ["die Daumen drücken", "幸運を祈る", "Ich drücke dir die Daumen."],
    ["ins Gras beißen", "死ぬ", "Der Held muss ins Gras beißen."],
    ["Schwein haben", "運がいい", "Du hast wirklich Schwein gehabt."],
    ["Bahnhof verstehen", "さっぱりわからない", "Ich verstehe nur Bahnhof."],
    ["die Nase voll haben", "うんざりしている", "Ich habe die Nase voll davon."],
    ["zwei Fliegen mit einer Klappe schlagen", "一石二鳥を得る", "Damit schlagen wir zwei Fliegen mit einer Klappe."],
    ["um den heißen Brei herumreden", "核心を避けて話す", "Rede nicht um den heißen Brei herum."],
    ["den Nagel auf den Kopf treffen", "核心を突く", "Du triffst den Nagel auf den Kopf."],
    ["die Katze aus dem Sack lassen", "秘密をばらす", "Jetzt lässt er die Katze aus dem Sack."],
    ["Da liegt der Hund begraben", "そこが問題の核心だ", "Da liegt der Hund begraben."],
    ["alles in Butter", "すべて順調である", "Keine Sorge, alles ist in Butter."]
  ],
  it: [
    ["in bocca al lupo", "幸運を祈る、頑張って", "In bocca al lupo per l'esame!"],
    ["costare un occhio della testa", "非常に高い", "Quella borsa costa un occhio della testa."],
    ["essere al settimo cielo", "大喜びしている", "Sono al settimo cielo."],
    ["avere le mani bucate", "浪費する", "Lui ha le mani bucate."],
    ["prendere due piccioni con una fava", "一石二鳥を得る", "Così prendiamo due piccioni con una fava."],
    ["piovere a catinelle", "土砂降りになる", "Piove a catinelle."],
    ["rompere il ghiaccio", "緊張をほぐす", "Una battuta può rompere il ghiaccio."],
    ["non vedere l'ora di", "心待ちにする", "Non vedo l'ora di partire."],
    ["avere la testa fra le nuvole", "ぼんやりしている", "Oggi hai la testa fra le nuvole."],
    ["fare orecchie da mercante", "聞こえないふりをする", "Fa orecchie da mercante."],
    ["in gamba", "有能な、しっかりした", "Sei proprio in gamba!"],
    ["essere in gamba", "有能である", "Lei è una persona in gamba."]
  ]
};
